const SCENARIOS=[
{id:'C1',game:'cash',street:'preflop',difficulty:'basic',title:'BTNからのオープン',concept:'ポジション',tags:['ポジション','オープンレンジ'],heroPosition:'BTN',stack:100,pot:1.5,toCall:0,hand:['A♠','5♠'],board:[],actionLine:'UTG〜COがフォールド。SBとBBが残っています。',prompt:'BTNでA5s。あなたの最初のアクションは？',actions:[['fold','フォールド',5],['call','リンプ',15],['raise_small','2.2〜2.5BBにレイズ',100],['raise_large','4BBにレイズ',55]],best:'raise_small',feedback:'A5sはBTNの標準的なオープン候補です。小さなレイズで広いレンジを効率よく運用します。',gto:'BTNはポジション優位が大きく、A5sは高頻度オープンです。',exploit:'ブラインドが過剰にフォールドするなら、さらに広くオープンできます。',key:'ポジションが良いほど、同じハンドでも参加価値が上がります。'},
{id:'C2',game:'cash',street:'preflop',difficulty:'intermediate',title:'BBディフェンス',concept:'ポットオッズ',tags:['ポットオッズ','BBディフェンス'],heroPosition:'BB',villainPosition:'BTN',stack:100,pot:4,toCall:1.5,hand:['K♣','9♣'],board:[],actionLine:'BTNが2.5BBにオープン。SBはフォールド。',prompt:'BBのK9s。BTNのオープンにどう対応しますか？',actions:[['fold','フォールド',30],['call','コール',100],['threebet','9BBに3ベット',72],['jam','オールイン',0]],best:'call',feedback:'K9sはBTNの広いレンジに対して十分なエクイティがあり、BBの価格でコールできます。',gto:'BBはすでに1BBを投資しているため必要エクイティが低く、K9sは主にコールです。',exploit:'BTNが3ベットに過剰フォールドするなら3ベット比率を増やせます。',key:'ハンドの絶対強度ではなく、価格と相手レンジを同時に見ます。'},
{id:'C3',game:'cash',street:'preflop',difficulty:'intermediate',title:'SBからの3ベット',concept:'レンジ優位',tags:['3ベット','ポジション不利'],heroPosition:'SB',villainPosition:'BTN',stack:100,pot:4,toCall:2,hand:['A♦','J♣'],board:[],actionLine:'BTNが2.5BBにオープン。あなたはSBです。',prompt:'AJoを持っています。最も合理的な対応は？',actions:[['fold','フォールド',20],['call','コール',55],['threebet','10〜11BBに3ベット',100],['jam','オールイン',5]],best:'threebet',feedback:'SBはポストフロップで不利になるため、AJoは3ベットで主導権を取る価値が高いハンドです。',gto:'SBはコールを絞り、3ベット中心に構成しやすいポジションです。',exploit:'BTNが4ベットをほとんどしないなら広めに3ベットできます。',key:'SBでは「コールできるか」より、不利な位置で利益を残せるかを考えます。'},
{id:'C4',game:'cash',street:'preflop',difficulty:'basic',title:'UTGオープンへの対応',concept:'レンジ認識',tags:['相手レンジ','ドミネーション'],heroPosition:'BB',villainPosition:'UTG',stack:100,pot:4.5,toCall:2,hand:['K♠','10♦'],board:[],actionLine:'UTGが3BBにオープン。全員フォールドしてBBまで回りました。',prompt:'KToでどう対応しますか？',actions:[['fold','フォールド',100],['call','コール',45],['threebet','11BBに3ベット',20],['jam','オールイン',0]],best:'fold',feedback:'UTGの強いレンジに対してKToはドミネーションされやすいハンドです。',gto:'BBの価格は良くても、UTGレンジ相手ではフォールドが自然です。',exploit:'UTGが明確にルースならコール候補になります。',key:'ブロードウェイだから参加するのではなく、支配される組み合わせを避けます。'},
{id:'F1',game:'cash',street:'postflop',difficulty:'basic',title:'ドライボードのCB',concept:'レンジ優位',tags:['CB','ベットサイズ'],heroPosition:'BTN',villainPosition:'BB',stack:97.5,pot:5.5,toCall:0,hand:['A♠','K♥'],board:['A♥','7♣','2♠'],actionLine:'BTNオープン、BBコール。フロップでBBチェック。',prompt:'トップペア・トップキッカー。扱いやすいサイズは？',actions:[['check','チェック',70],['bet_small','約33%ベット',100],['bet_medium','約70%ベット',62],['bet_pot','ポットベット',30]],best:'bet_small',feedback:'A72レインボーはBTN側のレンジ優位が大きく、小さく広くベットしやすいボードです。',gto:'小さいサイズで弱いAxやポケットペアから価値を取り、レンジ全体を運用できます。',exploit:'相手がサイズに関係なくコールするなら、強いAxでは少し大きくできます。',key:'強いハンドだから大きく打つのではなく、ボード全体のレンジ優位を見ます。'},
{id:'F2',game:'cash',street:'postflop',difficulty:'intermediate',title:'ウェットボードのディフェンス',concept:'ドロー管理',tags:['ドロー','コールレンジ'],heroPosition:'BB',villainPosition:'BTN',stack:95,pot:7.3,toCall:1.8,hand:['K♥','Q♥'],board:['Q♣','9♥','4♥'],actionLine:'BTNオープン、BBコール。チェック後にBTNが約33%ベット。',prompt:'トップペア＋フラッシュドロー。どう対応しますか？',actions:[['fold','フォールド',0],['call','コール',100],['raise_small','小さくチェックレイズ',78],['jam','オールイン',28]],best:'call',feedback:'強いショーダウンバリューとドローを持ち、相手のブラフを残すコールが標準的です。',gto:'レイズも可能ですが、このコンボはコールレンジを守る役割があります。',exploit:'弱いQxを降りない相手にはレイズ価値が上がります。',key:'強いドロー付きメイドハンドでも、必ずレイズする必要はありません。'},
{id:'R1',game:'cash',street:'postflop',difficulty:'advanced',title:'リバーのブラフキャッチ',concept:'相手傾向',tags:['ブラフキャッチ','エクスプロイト'],heroPosition:'BTN',villainPosition:'BB',stack:70,pot:32,toCall:40,hand:['A♣','Q♦'],board:['A♥','K♠','7♣','2♦','2♣'],actionLine:'リバーでBBが125%のドンクベット。相手は普段かなりパッシブ。',prompt:'トップペアで大きなリバーベットを受けました。',actions:[['fold','フォールド',100],['call','コール',32],['raise','小さくレイズ',0],['jam','オールイン',0]],best:'fold',feedback:'パッシブな相手の突然のオーバーベットは、実戦ではバリュー寄りになりやすい状況です。',gto:'必要勝率を満たすため、無差別にワンペアをコールできません。',exploit:'ブラフ不足が確認できる相手には強いワンペアでもフォールドします。',key:'ブラフキャッチは自分の強さより、相手のブラフ頻度で決めます。'},
{id:'T1',game:'tournament',street:'preflop',difficulty:'basic',title:'30BBのオープン',concept:'スタック深度',tags:['トーナメント','オープンサイズ'],heroPosition:'CO',stack:30,pot:2.5,toCall:0,hand:['A♦','J♦'],board:[],actionLine:'アンティあり。UTGとMPがフォールド。',prompt:'COのAJs。最初のアクションは？',actions:[['fold','フォールド',0],['call','リンプ',22],['raise_small','2〜2.2BBにレイズ',100],['jam','30BBオールイン',12]],best:'raise_small',feedback:'30BBでは小さなオープンでレンジを広く保ち、3ベットへの対応余地を残します。',gto:'アンティによりスチール価値が高く、AJsは明確なオープンです。',exploit:'後ろがコール過多なら、バリューハンドのサイズを少し上げられます。',key:'スタック深度に応じてレイズサイズと継続計画を変えます。'},
{id:'T2',game:'tournament',street:'preflop',difficulty:'intermediate',title:'15BBのリスチール',concept:'プッシュフォールド',tags:['オールイン','フォールドエクイティ'],heroPosition:'SB',villainPosition:'BTN',stack:15,pot:5,toCall:2,hand:['A♠','5♠'],board:[],actionLine:'アンティあり。BTNが2BBにオープン。',prompt:'SBのA5s。最も有力な選択は？',actions:[['fold','フォールド',30],['call','コール',45],['threebet','5.5BBに3ベット',62],['jam','15BBオールイン',100]],best:'jam',feedback:'A5sはAブロッカーとコールされた際のエクイティを持ち、15BBのリスチール候補です。',gto:'中途半端な3ベットではコミットしやすいため、オールインが扱いやすいです。',exploit:'BTNがほとんど降りないなら、よりリニアなバリューレンジに寄せます。',key:'ショートスタックではフォールドエクイティを重視します。'},
{id:'T3',game:'tournament',street:'preflop',difficulty:'advanced',title:'バブルのUTG判断',concept:'ICM',tags:['ICM','リスクプレミアム'],heroPosition:'UTG',stack:20,pot:2.5,toCall:0,hand:['A♣','9♦'],board:[],actionLine:'残り11人、10人入賞。中位スタックで、後ろに大スタック。',prompt:'UTGのA9o。基本的な選択は？',actions:[['fold','フォールド',100],['raise_small','2BBにレイズ',48],['call','リンプ',15],['jam','20BBオールイン',5]],best:'fold',feedback:'バブルでは失うチップの賞金価値が大きく、境界ハンドは絞る必要があります。',gto:'チップEVでオープン候補でも、ICMによりフォールドへ移る組み合わせがあります。',exploit:'テーブル全体が過剰フォールドしている場合はスチール価値が上がります。',key:'チップが増えることと賞金期待値が増えることは一致しません。'}
].map(s=>({...s,actions:s.actions.map(([id,label,score])=>({id,label,score}))}));

const DEFAULT={history:[],currentScenarioId:null,handCounter:1,streak:0,bestStreak:0,settings:{modeCash:true,modeTournament:true,streetPreflop:true,streetPostflop:true,difficulty:'intermediate',adaptiveMode:true,coachStyle:'balanced'}};
let state=loadState(),currentScenario=null,answered=false,deferredInstallPrompt=null;
const el=id=>document.getElementById(id);
function loadState(){try{const x=JSON.parse(localStorage.getItem('pokerDecisionLab'));return {...DEFAULT,...x,settings:{...DEFAULT.settings,...(x?.settings||{})}}}catch{return structuredClone(DEFAULT)}}
function saveState(){localStorage.setItem('pokerDecisionLab',JSON.stringify(state))}
function cardHtml(card){if(!card)return '<span class="card-face placeholder">?</span>';const suit=card.slice(-1),rank=card.slice(0,-1),red='♥♦'.includes(suit)?' red':'';return `<span class="card-face${red}">${rank}${suit}</span>`}
function renderCards(node,cards,n=0){const a=[...cards];while(a.length<n)a.push('');node.innerHTML=a.map(cardHtml).join('')}
function diffLabel(x){return {basic:'Basic',intermediate:'Intermediate',advanced:'Advanced'}[x]||x}
function grade(score){return score>=90?['A','高品質な判断','']:score>=70?['B','概ね妥当','grade-b']:score>=40?['C','改善余地あり','grade-c']:['D','期待値を失いやすい判断','grade-d']}
function weakness(){const m={};state.history.forEach(h=>(h.tags||[]).forEach(t=>{m[t]??={sum:0,n:0};m[t].sum+=h.score;m[t].n++}));return Object.fromEntries(Object.entries(m).map(([k,v])=>[k,v.sum/v.n]))}
function pool(){const s=state.settings;let a=SCENARIOS.filter(x=>((x.game==='cash'&&s.modeCash)||(x.game==='tournament'&&s.modeTournament))&&((x.street==='preflop'&&s.streetPreflop)||(x.street==='postflop'&&s.streetPostflop)));if(!a.length)a=[...SCENARIOS];if(s.difficulty==='basic')a=a.filter(x=>x.difficulty==='basic');if(s.difficulty==='advanced')a=a.filter(x=>x.difficulty==='advanced');if(s.difficulty==='intermediate'){const p=a.filter(x=>x.difficulty!=='advanced');if(p.length)a=p}return a.length?a:[...SCENARIOS]}
function chooseScenario(){let a=pool().filter(x=>x.id!==currentScenario?.id);if(!a.length)a=pool();if(state.settings.adaptiveMode&&state.history.length>=3){const w=weakness(),weighted=[];a.forEach(s=>{const v=s.tags.reduce((z,t)=>z+(w[t]??75),0)/s.tags.length,n=v<55?5:v<70?3:1;for(let i=0;i<n;i++)weighted.push(s)});a=weighted}return a[Math.floor(Math.random()*a.length)]}
function renderScenario(s){currentScenario=s;state.currentScenarioId=s.id;answered=false;saveState();el('scenarioType').textContent=s.game==='cash'?`Cash ${s.stack}BB`:`Tournament ${s.stack}BB`;el('difficultyBadge').textContent=diffLabel(s.difficulty);el('handNumber').textContent=`HAND #${String(state.handCounter).padStart(3,'0')}`;el('heroPosition').textContent=s.heroPosition;el('effectiveStack').textContent=`${s.stack} BB`;el('potSize').textContent=`${s.pot} BB`;el('toCall').textContent=`${s.toCall} BB`;el('actionLine').textContent=s.actionLine;el('scenarioTitle').textContent=s.title;el('conceptTag').textContent=s.concept;el('scenarioPrompt').textContent=s.prompt;renderCards(el('holeCards'),s.hand);renderCards(el('boardCards'),s.board,s.street==='postflop'?5:0);document.querySelectorAll('.seat').forEach(n=>n.classList.remove('hero','active-villain'));document.querySelector(`.seat-${s.heroPosition.toLowerCase()}`)?.classList.add('hero');if(s.villainPosition)document.querySelector(`.seat-${s.villainPosition.toLowerCase()}`)?.classList.add('active-villain');['UTG','MP','CO','BTN','SB','BB'].forEach(p=>el(`seat${p}`).textContent=`${s.stack} BB`);el('decisionButtons').innerHTML='';s.actions.forEach(a=>{const b=document.createElement('button');b.type='button';b.className='action-button';b.textContent=a.label;b.dataset.action=a.id;b.addEventListener('click',()=>submit(a.id));el('decisionButtons').appendChild(b)});el('feedback').classList.add('hidden');el('aiCurrentResponse').classList.add('hidden')}
function submit(id){if(answered)return;answered=true;const a=currentScenario.actions.find(x=>x.id===id),best=currentScenario.actions.find(x=>x.id===currentScenario.best),[g,title,cl]=grade(a.score);el('gradeBadge').textContent=g;el('gradeBadge').className=`grade-badge ${cl}`;el('feedbackTitle').textContent=title;el('feedbackSummary').textContent=`${a.label}：${currentScenario.feedback}`;el('gtoNote').textContent=currentScenario.gto;el('exploitNote').textContent=currentScenario.exploit;el('keyPoint').textContent=currentScenario.key;el('feedback').classList.remove('hidden');document.querySelectorAll('.action-button').forEach(b=>{b.disabled=true;if(b.dataset.action===currentScenario.best)b.style.borderColor='var(--accent)';if(b.dataset.action===id&&id!==currentScenario.best)b.style.borderColor='var(--danger)'});state.streak=a.score>=90?state.streak+1:0;state.bestStreak=Math.max(state.bestStreak,state.streak);state.history.unshift({timestamp:new Date().toISOString(),scenarioId:currentScenario.id,title:currentScenario.title,game:currentScenario.game,street:currentScenario.street,hand:currentScenario.hand.join(' '),position:currentScenario.heroPosition,selected:a.label,selectedId:id,recommended:best.label,score:a.score,tags:currentScenario.tags});state.history=state.history.slice(0,300);state.handCounter++;saveState();renderMetrics();renderDashboard()}
function renderMetrics(){const n=state.history.length,avg=n?Math.round(state.history.reduce((s,x)=>s+x.score,0)/n):null;el('totalDecisions').textContent=n;el('avgScore').textContent=avg??'--';el('streak').textContent=state.streak;const w=Object.entries(weakness()).sort((a,b)=>a[1]-b[1])[0];el('topLeak').textContent=w?`${w[0]} ${Math.round(w[1])}`:'未判定'}
function avg(a){return a.length?a.reduce((s,x)=>s+x.score,0)/a.length:null}
function renderDashboard(){const entries=Object.entries(weakness()).sort((a,b)=>a[1]-b[1]);el('conceptScores').innerHTML=entries.length?entries.map(([t,v])=>`<div class="concept-row"><div class="concept-row-head"><span>${t}</span><strong>${Math.round(v)}</strong></div><div class="progress-track"><div class="progress-fill" style="width:${Math.max(3,v)}%"></div></div></div>`).join(''):'<p class="small">プレイすると弱点分析を表示します。</p>';const h=state.history,pre=avg(h.filter(x=>x.street==='preflop')),post=avg(h.filter(x=>x.street==='postflop')),low=h.filter(x=>x.score<60),items=[];if(!h.length)items.push(['○','データ待ち','プレイを開始すると判断傾向を表示します。']);else{items.push(['↗',`平均スコア ${Math.round(avg(h))}`,`最高連続正解は${state.bestStreak}回です。`]);if(pre!==null&&post!==null)items.push(['◎',pre<post?'プリフロップが課題':'ポストフロップが課題',`プリフロップ ${Math.round(pre)}、ポストフロップ ${Math.round(post)}。`]);if(low.length){const c={};low.flatMap(x=>x.tags||[]).forEach(t=>c[t]=(c[t]||0)+1);const top=Object.entries(c).sort((a,b)=>b[1]-a[1])[0];items.push(['!',`優先復習：${top[0]}`,`低スコア判断で${top[1]}回出現しています。`])}}el('behaviorInsights').innerHTML=items.map(x=>`<div class="insight-item"><div class="insight-mark">${x[0]}</div><div><strong>${x[1]}</strong><p>${x[2]}</p></div></div>`).join('');el('historyBody').innerHTML=h.slice(0,30).map(x=>`<tr><td>${new Date(x.timestamp).toLocaleString('ja-JP',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})}</td><td>${x.title}<br><span class="small">${x.position} ${x.hand}</span></td><td>${x.selected}</td><td>${x.recommended}</td><td class="${x.score>=80?'score-good':x.score>=50?'score-mid':'score-low'}">${x.score}</td><td>${x.tags.join(' / ')}</td></tr>`).join('')||'<tr><td colspan="6" class="small">履歴はまだありません。</td></tr>'}
function reviewData(){return {game:el('reviewGame').value,street:el('reviewStreet').value,position:el('reviewPosition').value,stackBB:+el('reviewStack').value,hand:el('reviewHand').value.trim(),board:el('reviewBoard').value.trim(),potBB:+el('reviewPot').value,callBB:+el('reviewCall').value,actionHistory:el('reviewAction').value.trim(),thought:el('reviewThought').value.trim(),villain:el('reviewVillain').value.trim()}}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function renderReview(d){const req=d.callBB>0?d.callBB/(d.potBB+2*d.callBB):0,notes=[];if(d.callBB>0)notes.push(`コールに必要な最低勝率は概算で${Math.round(req*100)}%です。`);else notes.push('ベットの目的を、バリュー・ブラフ・エクイティ否定のどれかで明確にしてください。');if(d.position==='SB')notes.push('SBは不利な位置なので、曖昧なコールを減らします。');if(d.stackBB<=15)notes.push('15BB以下ではプッシュ・フォールドを優先して比較します。');else if(d.stackBB<=30)notes.push('低SPRでは小さいベットでもスタックを入れ切れます。');if(/パッシブ|ブラフ.*少|タイト/i.test(d.villain))notes.push('パッシブな相手の大きなリバーアクションにはフォールドを増やせます。');if(/コール.*多|降りない/i.test(d.villain))notes.push('コール過多の相手にはブラフを減らし、バリューを増やします。');el('reviewEmpty').classList.add('hidden');el('reviewOutput').classList.remove('hidden');el('reviewOutput').innerHTML=`<div class="review-card"><h3>状況整理</h3><p>${d.game==='cash'?'キャッシュ':'トーナメント'} / ${d.street} / ${d.position} / ${d.stackBB}BB</p><p>ハンド: ${esc(d.hand||'未入力')}　ボード: ${esc(d.board||'なし')}</p></div><div class="review-card"><h3>数値チェック</h3><p>${d.callBB>0?`必要勝率（概算）: <strong>${Math.round(req*100)}%</strong>`:'コール額なし'}</p></div><div class="review-card"><h3>コーチの観点</h3><ul>${notes.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="review-card"><h3>自分で答える3問</h3><ul><li>相手の推定レンジは各ストリートでどう変わりましたか？</li><li>より高いEVの代替アクションはありますか？</li><li>同じラインをブラフとバリューの両方で取れていますか？</li></ul></div>`}
async function callAi(payload,target,button){target.classList.remove('hidden');target.textContent='分析中…';button.disabled=true;try{const r=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({payload,style:state.settings.coachStyle})}),b=await r.json();if(!r.ok)throw Error(b.error||'AI分析に失敗しました');target.textContent=b.analysis;el('apiStatus').textContent='LLM接続済み'}catch(e){target.textContent=`公開版ではLLM詳細分析は未接続です。\n${e.message}\n\nゲームとローカル分析は利用できます。`;el('apiStatus').textContent='ローカル分析'}finally{button.disabled=false}}
function syncSettings(){Object.entries(state.settings).forEach(([k,v])=>{const n=el(k);if(n)n.type==='checkbox'?n.checked=v:n.value=v})}
function saveSettings(){state.settings={modeCash:el('modeCash').checked,modeTournament:el('modeTournament').checked,streetPreflop:el('streetPreflop').checked,streetPostflop:el('streetPostflop').checked,difficulty:el('difficulty').value,adaptiveMode:el('adaptiveMode').checked,coachStyle:el('coachStyle').value};if(!state.settings.modeCash&&!state.settings.modeTournament)state.settings.modeCash=true;if(!state.settings.streetPreflop&&!state.settings.streetPostflop)state.settings.streetPreflop=true;syncSettings();saveState();el('settingsSaved').textContent='保存しました';setTimeout(()=>el('settingsSaved').textContent='',1600)}
function exportData(){const b=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),history:state.history,settings:state.settings},null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=`poker-history-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(u)}
function ios(){return /iphone|ipad|ipod/i.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1)}
function standalone(){return matchMedia('(display-mode: standalone)').matches||navigator.standalone===true}
function openGuide(){el('installModal').classList.remove('hidden');document.body.style.overflow='hidden'}
function closeGuide(){el('installModal').classList.add('hidden');document.body.style.overflow=''}
function updatePwa(){const status=el('pwaStatusText');if(standalone()){el('installBanner').classList.add('hidden');if(status)status.textContent='ホーム画面アプリとして起動中です。';return}if(ios()&&localStorage.getItem('pokerInstallBannerDismissed')!=='1')el('installBanner').classList.remove('hidden');if(status)status.textContent=ios()?'Safariの共有メニューからホーム画面へ追加できます。':'iPhoneではSafariからホーム画面へ追加してください。'}
async function install(){if(deferredInstallPrompt){deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;updatePwa()}else openGuide()}
function bind(){document.querySelectorAll('.tab').forEach(t=>t.addEventListener('click',()=>{document.querySelectorAll('.tab,.tab-panel').forEach(x=>x.classList.remove('active'));t.classList.add('active');el(t.dataset.tab).classList.add('active');if(t.dataset.tab==='dashboard')renderDashboard()}));el('newHandTop').onclick=el('nextHand').onclick=()=>renderScenario(chooseScenario());el('runLocalReview').onclick=()=>renderReview(reviewData());el('runAiReview').onclick=()=>{const d=reviewData();renderReview(d);const box=document.createElement('div');box.className='ai-response';el('reviewOutput').prepend(box);callAi({type:'manual_hand_review',...d},box,el('runAiReview'))};el('askAiCurrent').onclick=()=>callAi({type:'scenario_review',scenario:currentScenario,userDecision:state.history[0]?.selected},el('aiCurrentResponse'),el('askAiCurrent'));el('saveSettings').onclick=saveSettings;el('exportData').onclick=exportData;el('clearHistory').onclick=()=>{if(confirm('成績履歴をすべて削除しますか？')){state.history=[];state.streak=0;saveState();renderMetrics();renderDashboard()}};['installAppTop','showInstallGuide','showInstallGuideSettings'].forEach(id=>el(id)?.addEventListener('click',install));['closeInstallGuide','closeInstallGuideBottom'].forEach(id=>el(id)?.addEventListener('click',closeGuide));el('dismissInstallBanner').onclick=()=>{localStorage.setItem('pokerInstallBannerDismissed','1');el('installBanner').classList.add('hidden')};el('installModal').onclick=e=>{if(e.target===el('installModal'))closeGuide()};addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e});if('serviceWorker'in navigator&&location.protocol.startsWith('http'))addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(console.warn))}
function boot(){bind();syncSettings();renderMetrics();renderDashboard();updatePwa();renderScenario(SCENARIOS.find(x=>x.id===state.currentScenarioId)||chooseScenario())}boot();