window.POKER_HANDS = [...(window.POKER_HANDS || []),
{
      id:'AQ_PASSIVE_RIVER',title:'AQ：パッシブ相手のリバーオーバーベット',game:'cash',difficulty:'advanced',stack:100,hero:'BTN',villain:'BB',hand:['A♣','Q♦'],concept:'相手傾向とブラフキャッチ',intro:'相手は普段かなりパッシブで、リバーの大きなブラフが少ないタイプです。理論と実戦調整を分けて考えます。',
      steps:[
        {street:'preflop',board:[],pot:1.5,toCall:0,stack:100,villainAction:'UTG〜COフォールド',situation:'BTNでA♣Q♦。',prompt:'プリフロップは？',after:'BBがコール。',choices:[window.pcChoice('fold','フォールド',0,true,'明確なオープンです。'),window.pcChoice('limp','リンプ',20,false,'強いレンジを受動的に運用しています。'),window.pcChoice('raise','2.2〜2.5BBレイズ',100,false,'標準的なBTNオープンです。'),window.pcChoice('large','5BBレイズ',48,false,'大きすぎてレンジ全体を運用しにくくします。')],best:'raise'},
        {street:'flop',board:['A♥','K♠','7♣'],pot:5.5,toCall:0,stack:97.5,villainAction:'BBチェック',situation:'トップペアQキッカー。相手の弱いAx、Kx、ガットショットから価値を取れます。',prompt:'フロップは？',after:'BBがコール。ターン2♦。',choices:[window.pcChoice('check','チェック',72,false,'成立しますが、弱いレンジからのバリューを逃します。'),window.pcChoice('small','約33%ベット',100,false,'小さく広く打てるボードです。'),window.pcChoice('large','約75%ベット',60,false,'弱いKxやポケットを降ろしすぎます。'),window.pcChoice('pot','ポットベット',32,false,'サイズが目的に合いません。')],best:'small'},
        {street:'turn',board:['A♥','K♠','7♣','2♦'],pot:9.1,toCall:0,stack:95.7,villainAction:'BBチェック',situation:'ブランクターン。相手のAxに対してはキッカー差があり、Kxからは追加バリューが取れます。',prompt:'ターンの方針は？',after:'BBがコール。リバー2♣。',choices:[window.pcChoice('check','チェックバック',82,false,'ショーダウン価値を守る選択として妥当です。'),window.pcChoice('medium','約55%ベット',100,false,'弱いAxとKxからバリューを取りやすいです。'),window.pcChoice('over','オーバーベット',42,false,'AQをこのサイズへ入れる必要はありません。'),window.pcChoice('jam','オールイン',12,false,'過剰なポラライズです。')],best:'medium'},
        {street:'river',board:['A♥','K♠','7♣','2♦','2♣'],pot:19.1,toCall:24,stack:90.7,villainAction:'BBが約125%のドンクベット',situation:'パッシブな相手が突然オーバーベット。自然なバリューは2x、AK、A7などで、ブラフ候補は限定的です。',prompt:'AQでどうしますか？',after:'ハンド終了。',choices:[window.pcChoice('fold','フォールド',100,true,'相手傾向を反映し、ブラフ不足へ大きく調整しています。'),window.pcChoice('call','コール',34,false,'理論上のブラフキャッチでも、実戦ではブラフ不足が大きな問題です。'),window.pcChoice('raise','小さくレイズ',0,false,'より弱いハンドからコールされず、強いハンドにだけ続行されます。'),window.pcChoice('jam','オールイン',0,false,'バリューとして薄く、ブラフとしてもブロッカーが不適切です。')],best:'fold'}
      ],overall:'前半は標準的なバリューラインを取りつつ、リバーだけは相手の明確なブラフ不足へ強くエクスプロイトするハンドです。'},
{
      id:'QQ_3BET_POT',title:'QQ：3ベットポットのオーバーカード',game:'cash',difficulty:'advanced',stack:100,hero:'CO',villain:'BTN',hand:['Q♠','Q♦'],concept:'レンジ優位の変化',intro:'BTNから3ベットを受けた3ベットポット。フロップでは強いですが、ターンのKで相対強度が変わります。',
      steps:[
        {street:'preflop',board:[],pot:4,toCall:7.5,stack:100,villainAction:'COが2.5BBオープン、BTNが10BBへ3ベット',situation:'COでQ♠Q♦。ブラインドはフォールド。',prompt:'3ベットへの対応は？',after:'BTNがコールし、4ベットポットまたは強いレンジ同士でフロップへ。',choices:[window.pcChoice('fold','フォールド',0,true,'QQをBTNの3ベットへ降りるのは過剰です。'),window.pcChoice('call','コール',88,false,'レンジを守るコールとして十分成立します。'),window.pcChoice('fourbet','23BBへ4ベット',100,false,'BTNの広い3ベットへ明確なバリュー4ベットです。'),window.pcChoice('jam','100BBオールイン',48,false,'通常サイズの4ベットを飛ばす必要はありません。')],best:'fourbet'},
        {street:'flop',board:['J♣','8♠','5♠'],pot:47,toCall:0,stack:77,villainAction:'BTNチェック',situation:'オーバーペア。相手にはJJ、AK、AQ、TT、スーテッド系が残ります。',prompt:'フロップの方針は？',after:'BTNがコール。ターンK♦。',choices:[window.pcChoice('check','チェックバック',82,false,'レンジ保護として成立します。'),window.pcChoice('small','約25%ベット',100,false,'4ベット側のレンジ優位を使い、小さく広く打てます。'),window.pcChoice('medium','約60%ベット',63,false,'ポットが大きく、サイズを大きくする必要はありません。'),window.pcChoice('jam','オールイン',28,false,'弱いレンジを降ろし、強いレンジにだけ続行されます。')],best:'small'},
        {street:'turn',board:['J♣','8♠','5♠','K♦'],pot:59,toCall:0,stack:71,villainAction:'BTNチェック',situation:'Kが落ち、AKが改善しました。QQは依然ショーダウン価値がありますが、3ストリートの大きなバリューは難しくなります。',prompt:'ターンは？',after:'チェックバック。リバー2♥。',choices:[window.pcChoice('check','チェックバック',100,false,'ショーダウン価値を守り、リバーの判断を簡単にします。'),window.pcChoice('small','約25%ベット',70,false,'薄いベットとして可能ですが、コールされるレンジが強くなります。'),window.pcChoice('large','約70%ベット',32,false,'Kx優位の相手レンジに対し過剰です。'),window.pcChoice('jam','オールイン',10,false,'QQをバリューにもブラフにも中途半端に扱っています。')],best:'check'},
        {street:'river',board:['J♣','8♠','5♠','K♦','2♥'],pot:59,toCall:18,stack:71,villainAction:'BTNが約30%ベット',situation:'小さいリバーベット。AK・KQ・スロープレイに加え、AQや外れスペードのブロックベット／ブラフもあり得ます。',prompt:'リバーは？',after:'ショーダウン。',choices:[window.pcChoice('fold','フォールド',55,true,'相手が極端にバリュー寄りでなければ、小さいサイズへは降りすぎです。'),window.pcChoice('call','コール',100,false,'価格が良く、相手の薄いバリューやブラフを含むレンジに対してコールできます。'),window.pcChoice('raise','小さくレイズ',20,false,'より弱いハンドからコールされにくいです。'),window.pcChoice('jam','オールイン',5,false,'QQをブラフへ変える適切なブロッカーがありません。')],best:'call'}
      ],overall:'フロップではレンジ優位を使い、ターンのKでバリュー頻度を落とし、リバーの小さいサイズには価格を理由にコールするラインです。'}
];
