window.POKER_HANDS = [...(window.POKER_HANDS || []),
{
      id:'AJS_20BB',title:'20BB AJs：トーナメントのスタック運用',game:'tournament',difficulty:'intermediate',stack:20,hero:'CO',villain:'BB',hand:['A♦','J♦'],concept:'低SPRとバリュー保護',intro:'アンティありのトーナメント。20BBではプリフロップサイズと、ポストフロップでスタックを入れる計画が重要です。',
      steps:[
        {street:'preflop',board:[],pot:2.5,toCall:0,stack:20,villainAction:'UTG・MPフォールド',situation:'COでA♦J♦。BTN、SB、BBが残っています。',prompt:'プリフロップは？',after:'BBがコール。',choices:[window.pcChoice('fold','フォールド',0,true,'明確なオープンです。'),window.pcChoice('limp','リンプ',20,false,'スチール価値を失います。'),window.pcChoice('raise','2〜2.2BBレイズ',100,false,'レンジを広く保ち、3ベットへの対応余地も残します。'),window.pcChoice('jam','20BBオールイン',35,false,'デッドマネーは取れますが、強いハンドの価値を下げます。')],best:'raise'},
        {street:'flop',board:['J♣','7♦','3♠'],pot:6.5,toCall:0,stack:17.9,villainAction:'BBチェック',situation:'トップペア・トップキッカー。SPRは約2.75で、2ストリート程度でスタックを入れられます。',prompt:'フロップは？',after:'BBがコール。ターン8♦。',choices:[window.pcChoice('check','チェック',65,false,'成立しますが、弱いJxや7xから価値を逃します。'),window.pcChoice('small','約30%ベット',100,false,'低SPRでレンジを広く継続しやすいサイズです。'),window.pcChoice('large','約75%ベット',70,false,'バリューは取れますが、レンジ全体には大きめです。'),window.pcChoice('jam','オールイン',35,false,'弱い継続レンジを降ろしすぎます。')],best:'small'},
        {street:'turn',board:['J♣','7♦','3♠','8♦'],pot:10.4,toCall:0,stack:15.9,villainAction:'BBチェック',situation:'ナッツフラッシュドローも加わりました。Jx、ペア＋ドロー、9Tなどから価値を取れます。',prompt:'ターンの方針は？',after:'BBがコール。リバー2♣。',choices:[window.pcChoice('check','チェックバック',72,false,'エクイティは守れますが、低SPRで取り切る価値を逃します。'),window.pcChoice('small','約30%ベット',78,false,'悪くありませんが、リバーに不自然なスタックが残ります。'),window.pcChoice('large','約65%ベット',100,false,'バリューと保護を両立し、リバーの残りスタックも扱いやすくします。'),window.pcChoice('jam','約1.5倍ポットのオールイン',55,false,'強いものの、弱いJxを降ろしすぎます。')],best:'large'},
        {street:'river',board:['J♣','7♦','3♠','8♦','2♣'],pot:23.8,toCall:0,stack:9.1,villainAction:'BBチェック',situation:'ドローが外れたブランクリバー。残りは約38%ポットです。',prompt:'リバーは？',after:'ハンド終了。',choices:[window.pcChoice('check','チェックバック',58,false,'ショーダウンできますが、Jxからの明確なバリューを逃します。'),window.pcChoice('small','3BBベット',72,false,'コールは得やすいですが、残りスタックを活用し切れていません。'),window.pcChoice('jam','9.1BBオールイン',100,false,'SPR設計どおり、弱いJxや2ペア候補へ最大バリューを取れます。'),window.pcChoice('over','20BB相当ベット',0,false,'実際のスタックを超える選択です。')],best:'jam'}
      ],overall:'20BBの小さいオープンから低SPRを作り、フロップは小さく、ターンでサイズを上げ、リバーに自然なオールインを残すスタック設計です。'}
];
