window.POKER_HANDS = [...(window.POKER_HANDS || []),
{
      id:'AK_BTN_A72',title:'BTNのAK：ドライボードで3ストリート',game:'cash',difficulty:'basic',stack:100,hero:'BTN',villain:'BB',hand:['A♠','K♥'],concept:'レンジ優位から薄いバリューまで',intro:'6-maxキャッシュ。BTNから参加し、BBとのヘッズアップになります。各ストリートでベットの目的をつなげてください。',
      steps:[
        {street:'preflop',board:[],pot:1.5,toCall:0,stack:100,villainAction:'UTG〜COがフォールド',situation:'BTNでA♠K♥。SBとBBが残っています。',prompt:'最初のアクションは？',after:'BBがコール。フロップへ。',choices:[window.pcChoice('fold','フォールド',0,true,'明確なオープンハンドを捨てています。'),window.pcChoice('limp','リンプ',25,false,'強いレンジを小さくまとめすぎます。'),window.pcChoice('raise','2.2〜2.5BBにレイズ',100,false,'広いBTNレンジを小さいサイズで効率よく運用できます。'),window.pcChoice('large','4BBにレイズ',65,false,'利益は出ますが、BTNのレンジ全体には大きすぎます。')],best:'raise'},
        {street:'flop',board:['A♥','7♣','2♠'],pot:5.5,toCall:0,stack:97.5,villainAction:'BBがチェック',situation:'A72レインボー。トップペア・トップキッカーです。',prompt:'フロップでどうしますか？',after:'BBがコール。ターンは9♥。',choices:[window.pcChoice('check','チェック',72,false,'チェックも可能ですが、弱いAxやポケットペアから取れるバリューを逃します。'),window.pcChoice('small','約33%ベット',100,false,'レンジ優位を使い、小さく広くバリューを取れます。'),window.pcChoice('medium','約70%ベット',62,false,'強いハンドですが、ボードに対してサイズが大きすぎます。'),window.pcChoice('pot','ポットベット',30,false,'相手の弱い継続レンジを降ろしすぎます。')],best:'small'},
        {street:'turn',board:['A♥','7♣','2♠','9♥'],pot:9.1,toCall:0,stack:95.7,villainAction:'BBがチェック',situation:'ターンでハートのドローが増えました。相手にはAx、7x、ポケット、ハートドローが残ります。',prompt:'ターンの方針は？',after:'BBがコール。リバーは2♣。',choices:[window.pcChoice('check','チェックバック',78,false,'ポットコントロールとして成立しますが、ドローと弱いAxからのバリューを一部逃します。'),window.pcChoice('small','約33%ベット',85,false,'悪くありませんが、ドローに与える価格がやや良すぎます。'),window.pcChoice('medium','約60%ベット',100,false,'Axとドローから取りながら、リバーの価値判断につなげられます。'),window.pcChoice('over','オーバーベット',45,false,'レンジ上の優位はありますが、AK単体では過剰です。')],best:'medium'},
        {street:'river',board:['A♥','7♣','2♠','9♥','2♣'],pot:20,toCall:0,stack:89.7,villainAction:'BBがチェック',situation:'ボードがペアになり、フラッシュドローは外れました。弱いAxから最後のバリューを取れる場面です。',prompt:'リバーの最終判断は？',after:'ショーダウン。',choices:[window.pcChoice('check','チェックバック',70,false,'安全ですが、弱いAxに対する薄いバリューを逃します。'),window.pcChoice('small','約35〜45%バリューベット',100,false,'弱いAxや9xの一部からコールを得やすいサイズです。'),window.pcChoice('large','約80%ベット',62,false,'コールされるレンジが強くなりすぎます。'),window.pcChoice('jam','オールイン',20,false,'このランアウトでAKを極端にポラライズする必要はありません。')],best:'small'}
      ],overall:'プリフロップのレンジ優位をフロップの小さいCB、ターンの保護を兼ねたバリュー、リバーの薄いバリューへつなぐハンドです。'},
{
      id:'KQ_BB_Q94',title:'BBのKQs：強いドロー付きトップペア',game:'cash',difficulty:'intermediate',stack:100,hero:'BB',villain:'BTN',hand:['K♥','Q♥'],concept:'コールレンジを守る',intro:'BTNの広いレンジに対し、BBからディフェンスします。強いハンドでも毎回レイズしないことがテーマです。',
      steps:[
        {street:'preflop',board:[],pot:4,toCall:1.5,stack:100,villainAction:'BTNが2.5BBにオープン、SBフォールド',situation:'BBでK♥Q♥。すでに1BBを投入しています。',prompt:'プリフロップの対応は？',after:'BTNがコールまたはポットが継続し、フロップへ。',choices:[window.pcChoice('fold','フォールド',5,true,'価格とハンド強度に対して降りすぎです。'),window.pcChoice('call','コール',100,false,'広いBTNレンジに対し、BBの価格を生かせます。'),window.pcChoice('threebet','9BBに3ベット',85,false,'十分強い選択ですが、コールレンジにも残したいコンボです。'),window.pcChoice('jam','オールイン',0,true,'100BBでは過剰です。')],best:'call'},
        {street:'flop',board:['Q♣','9♥','4♥'],pot:5.5,toCall:1.8,stack:97.5,villainAction:'チェック後、BTNが約33%ベット',situation:'トップペア＋Kハイフラッシュドロー。ショーダウンバリューと強い改善余地があります。',prompt:'フロップの対応は？',after:'コール後、ターンは2♣。',choices:[window.pcChoice('fold','フォールド',0,true,'強すぎるハンドを捨てています。'),window.pcChoice('call','コール',100,false,'相手のブラフを残し、コールレンジを強くできます。'),window.pcChoice('raise','小さくチェックレイズ',80,false,'有力ですが、このコンボはコール側にも必要です。'),window.pcChoice('jam','オールイン',38,false,'相手の弱いブラフを降ろし、強いレンジにだけ続行されやすくなります。')],best:'call'},
        {street:'turn',board:['Q♣','9♥','4♥','2♣'],pot:9.1,toCall:6,stack:95.7,villainAction:'BBチェック、BTNが約66%ベット',situation:'ブランクターン。相手はQx、オーバーペア、ドロー、ブラフを含みます。',prompt:'ターンでどうしますか？',after:'コール後、リバーはA♣。',choices:[window.pcChoice('fold','フォールド',20,true,'ドローとトップペアを持つため、まだ継続できます。'),window.pcChoice('call','コール',100,false,'相手のブラフを残しつつ、十分なエクイティを実現できます。'),window.pcChoice('raise','小さくレイズ',58,false,'強いハンドにだけ続行され、コールの利点を失いやすいです。'),window.pcChoice('jam','オールイン',42,false,'バリューとブラフの両方を降ろしすぎる可能性があります。')],best:'call'},
        {street:'river',board:['Q♣','9♥','4♥','2♣','A♣'],pot:21.1,toCall:14,stack:89.7,villainAction:'BBチェック、BTNが約66%ベット',situation:'ハートは外れ、Aが落ちました。相手のAxブラフがバリュー化し、Qxの相対価値が低下しています。',prompt:'リバーの判断は？',after:'ハンド終了。',choices:[window.pcChoice('fold','フォールド',100,true,'自然なバリューが増え、ブラフ候補が減るためフォールドが合理的です。'),window.pcChoice('call','コール',48,false,'相手が十分にブラフする確証が必要です。'),window.pcChoice('raise','ブラフレイズ',22,false,'K♥はハートをブロックしており、相手の外れドローを減らすため良いブラフ候補ではありません。'),window.pcChoice('jam','オールイン',5,false,'バリューにコールされ、弱いハンドを降ろすだけになりやすいです。')],best:'fold'}
      ],overall:'強いトップペア＋ドローをレイズせずコール側に残し、リバーでレンジとブロッカーが悪化したら降りる一貫したブラフキャッチ管理です。'}
];
